#define GRANTLEE_VERSION_MAJOR 5
#define GRANTLEE_VERSION_MINOR 1
#define GRANTLEE_VERSION_PATCH 0
#define GRANTLEE_VERSION_STRING "5.1.0"
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "5.1"
#define GRANTLEE_MIN_PLUGIN_VERSION 0
