QT.core_private.VERSION = 5.12.8
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.8 $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.8/QtCore
QT.core_private.frameworks =
QT.core_private.depends = core
QT.core_private.uses =
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = clock-gettime datetimeparser dlopen doubleconversion futimens getauxval getentropy glib glibc icu inotify linkat poll_ppoll renameat2 sha3-fast statx system-pcre2
QT.core_private.disabled_features = etw futimes gnu-libiconv iconv journald lttng poll_poll poll_pollts poll_select posix-libiconv slog2 syslog system-doubleconversion
QMAKE_LIBS_LIBRT = 
QMAKE_LIBS_LIBDL = 
QMAKE_LIBS_GLIB = /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libgthread-2.0.so /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libglib-2.0.so
QMAKE_INCDIR_GLIB = /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/glib-2.0 /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/glib-2.0/include
QMAKE_DEPENDS_ICU_CC = LIBDL
QMAKE_DEPENDS_ICU_LD = LIBDL
QMAKE_LIBS_ICU = /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libicui18n.so /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libicuuc.so /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libicudata.so
QMAKE_LIBS_LIBATOMIC = 
QMAKE_LIBS_PCRE2 = /home/book/100ask_imx6ull-sdk/Buildroot_2020.02.x/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libpcre2-16.so
